### ISSUE TITLE
Modify update script to update matrix

### ISSUE THREAD

**Issue by maresb** [maresb/micromamba-devcontainer#29]
Now that there is a matrix from #28, we should modify the [update script](https://github.com/mamba-org/micromamba-devcontainer/blob/main/scripts/update_base_image.py) so that the [matrix](https://github.com/mamba-org/micromamba-devcontainer/blob/b34ef0368aab25f63e6efa35335af0605f2ceba5/.github/workflows/publish_image.yml#L21-L22) is kept up-to-date.

CC @basnijholt

**Comment by basnijholt** [comment]
I am on it!

Any idea why only one image is pushed though?

**Comment by maresb** [comment]
I think it's because #28 didn't update the tags according to the base image, so I think the second-built image clobbered the first-built. We should fix that... :grin:

**Comment by basnijholt** [comment]
I do not understand the tagging very well.

I opened https://github.com/mamba-org/micromamba-devcontainer/pull/31 which updates the image tags correctly.

**Comment by maresb** [comment]
Ya, the combined workings of `docker/metadata-action` and `docker/docker-push-action` are pretty opaque.

`type=sha,enable=true,prefix=git-` means `f"git-{short_sha}"` and `type=raw,value=latest` means `"latest"`, and those get referenced for the push via `tags: ${{ steps.meta.outputs.tags }}`.

What would you like to be the tag of the cuda image?

**Comment by basnijholt** [comment]
OK I see!

What about https://github.com/mamba-org/micromamba-devcontainer/pull/32?
