### ISSUE TITLE
I'm missing access to "Settings" menu

### ISSUE THREAD

**Issue by maresb** [maresb/micromamba-devcontainer#3]
I'd like to be able to manage settings regarding protected branches, secrets, etc. but I seem to be locked out.

@wolfv and @jtpio, can you help me out?

![image](https://user-images.githubusercontent.com/15216687/185803793-a544a028-5b4b-4ee6-b79d-6e8921185471.png)

**Comment by jtpio** [comment]
@maresb I also don't have access to the "Settings" menu:

![image](https://user-images.githubusercontent.com/591645/185881274-f12dd817-2f09-4f12-9025-45b9ad3f3eb1.png)

The org owners should be able to help give access though: https://github.com/orgs/mamba-org/people?query=role%3Aowner

**Comment by maresb** [comment]
@wolfv, could you please grant me admin on this repo? I'd like to set up CD this weekend. Thanks!

**Comment by wolfv** [comment]
Hi @maresb so sorry it took me so long – first vacation then euroscipy. You have full admin access now!
